### Домашнее задание. Singular Value Decomposition

Разложить матрицу в SVD.

Цель: Выполнить сингулярное разложение в python и записать получившуюся матрицу преобразования для следующих матриц:

1)A=[3 7 5 2] 2)B=[0 1 3 2 3 1 0 1 0] 3)C=[5 7 6 4 2 1 3 4 1 3 3 4 5 4 1]

1. Установить набор библиотек Anaconda for Python 3.7: https://www.anaconda.com/distribution/
        

2. Запустить графическую среду Ipython Notebook (написав в терминале ipython notebook, либо используя графический интерфейс Anaconda)

3. Отразить код задания в Ipython Notebook

4. Прислать ссылку на репозиторий, в котором будет выложен Ipython Notebook с решением задачи

#### Task 1

In [27]:
# импортируем нампи
import numpy as np

In [28]:
# инициализируем массив
A = np.array([[3, 7],
              [5, 2]])

In [29]:
# проверяем форму массива
A.shape

(2, 2)

In [30]:
# применяем готовым метод для разложения матрицы
u, s, vh = np.linalg.svd(A, full_matrices=True) 
# If True (default), u and vh have the shapes (..., M, M) and (..., N, N), respectively. 
# Otherwise, the shapes are (..., M, K) and (..., K, N), respectively, where K = min(M, N).
# в нашем случае без разницы

In [31]:
# выводим формы получившихся матриц
u.shape, s.shape, vh.shape

((2, 2), (2,), (2, 2))

In [32]:
# методом np.allclose проверяем тождественность матрицы А и произведения матриц, полученных при разложении
np.allclose(A, np.dot(u * s, vh))

True

In [33]:
# выводим получившиеся матрицы
print("Ортогональная матрица: \n", u, "\n")
print("Диагональная матрица (записана в размерности (2,):\n", s, "\n")
print("Ортогональная матрица: \n", vh)

Ортогональная матрица: 
 [[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]] 

Диагональная матрица (записана в размерности (2,):
 [8.71337969 3.32821489] 

Ортогональная матрица: 
 [[-0.59455781 -0.80405286]
 [ 0.80405286 -0.59455781]]


#### Task 2

In [34]:
B = np.array([[0, 1, 3],
              [2, 3, 1],
             [0, 1, 0]])
B

array([[0, 1, 3],
       [2, 3, 1],
       [0, 1, 0]])

In [36]:
B.shape

(3, 3)

In [37]:
u, s, vh = np.linalg.svd(B, full_matrices=True) 

In [38]:
u.shape, s.shape, vh.shape

((3, 3), (3,), (3, 3))

In [39]:
np.allclose(B, np.dot(u * s, vh))

True

In [41]:
# выводим получившиеся матрицы
print("Ортогональная матрица: \n", u, "\n")
print("Диагональная матрица (записана в размерности (3,):\n", s, "\n")
print("Ортогональная матрица: \n", vh)

Ортогональная матрица: 
 [[-0.56667985  0.82277903  0.04368772]
 [-0.80674247 -0.54329657 -0.23236915]
 [-0.16745308 -0.16692366  0.97164601]] 

Диагональная матрица (записана в размерности (3,):
 [4.34019342 2.41561763 0.57228713] 

Ортогональная матрица: 
 [[-0.37175416 -0.72677875 -0.5775738 ]
 [-0.44982001 -0.40322372  0.79691442]
 [-0.81207192  0.5560605  -0.17701953]]


#### Task 3

In [83]:
C = np.array([[5, 7, 6, 4, 2],
              [1, 3, 4, 1, 3],
             [3, 4, 5, 4, 1]])
C

array([[5, 7, 6, 4, 2],
       [1, 3, 4, 1, 3],
       [3, 4, 5, 4, 1]])

In [84]:
C.shape

(3, 5)

In [98]:
u, s, vh = np.linalg.svd(C, full_matrices=False) 

In [99]:
u.shape, s.shape, vh.shape

((3, 3), (3,), (3, 5))

In [100]:
np.allclose(C, np.dot(u * s, vh[:3, :]))

True

In [101]:
# выводим получившиеся матрицы
print("Ортогональная матрица: \n", u, "\n")
print("Диагональная матрица (записана в размерности (3,):\n", s, "\n")
print("Ортогональная матрица: \n", vh)

Ортогональная матрица: 
 [[-0.75927897  0.23445293 -0.60706446]
 [-0.3639706  -0.92629427  0.09749016]
 [-0.53946348  0.29497584  0.78864974]] 

Диагональная матрица (записана в размерности (3,):
 [14.94713352  2.72739944  1.46440832] 

Ортогональная матрица: 
 [[-0.38661298 -0.57300074 -0.58264507 -0.37190679 -0.21073828]
 [ 0.41464331  0.01546935 -0.3019654   0.43683401 -0.73879941]
 [-0.39052151 -0.5479222   0.47174175  0.56256936 -0.09082761]]
